apiVersion: v1
kind: Service
metadata:
  name: libraryadvisor-service
spec:
  selector:
    app: libraryadvisor
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
  type: NodePort
